### ISSUE TITLE
How to actually use this?

### ISSUE THREAD

**Issue by radiospiel** [danhper/ex_cli#11]
Might be me, but I fail to see how to actually use this. There are examples that describe how to use the ExCLI DSL, so that is nice and shiny; but how is one supposed to go from there to an actual script, that can be run from the CLI?

**Comment by olivermicke** [comment]
I was having trouble getting started (still new to Elixir tho). I copied the `MyApp.SampleCLI` code and could not run `mix escript.build` without getting the following error: `Unknown command 'escript.build'`.

Removing `ExCLI.run!(MyApp.SampleCLI)` did the trick. In hindsight, `The basic usage is to use ExCLI.DSL to define your CLI, and ExCLI.run to run it` may explain it, but I'd still suggest to add it to the README. I wanted to make a PR but I'm not authorised to create a branch.
